export interface IVoteSeed {
    DT_GERACAO: string,
    HH_GERACAO: string,
    ANO_ELEICAO: string,
    SG_UF: string,
    CD_MUNICIPIO: string,
    NM_MUNICIPIO: string,
    CD_MUN_SIT_BIOMETRIA: string,
    DS_MUN_SIT_BIOMETRIA: string,
    NR_ZONA: string,
    NR_SECAO: string,
    CD_LOCAL_VOTACAO: string,
    CD_GENERO: string,
    DS_GENERO: string,
    CD_ESTADO_CIVIL: string,
    DS_ESTADO_CIVIL: string,
    CD_FAIXA_ETARIA: string,
    DS_FAIXA_ETARIA: string,
    CD_GRAU_ESCOLARIDADE: string,
    DS_GRAU_ESCOLARIDADE: string,
    QT_ELEITORES_PERFIL: string,
    QT_ELEITORES_BIOMETRIA: string,
    QT_ELEITORES_DEFICIENCIA: string,
    QT_ELEITORES_INC_NM_SOCIAL: string
}